import { Request, Response, NextFunction } from 'express';
import { pool } from '../config/db';
import { eleveSchema, eleveUpdateSchema } from '../validators/eleve.validator';
import { AppError } from '../middleware/errorHandler';

export const getEleves = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 20;
    const offset = (page - 1) * limit;
    const search = req.query.search as string;

    let query = 'SELECT * FROM Eleve';
    const queryParams: any[] = [];
    
    if (search) {
      query += ' WHERE nom LIKE ? OR prenom LIKE ? OR matricule LIKE ?';
      const searchParam = `%${search}%`;
      queryParams.push(searchParam, searchParam, searchParam);
    }
    
    // Total count for pagination
    let countQuery = 'SELECT COUNT(*) as total FROM Eleve';
    if (search) {
      countQuery += ' WHERE nom LIKE ? OR prenom LIKE ? OR matricule LIKE ?';
    }
    const [countRows]: any = await pool.query(countQuery, queryParams);
    const total = countRows[0].total;

    query += ' ORDER BY created_at DESC LIMIT ? OFFSET ?';
    queryParams.push(limit, offset);

    const [rows] = await pool.query(query, queryParams);

    res.status(200).json({
      success: true,
      data: rows,
      pagination: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    });
  } catch (error) {
    next(error);
  }
};

export const getEleveById = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const [rows]: any = await pool.query('SELECT * FROM Eleve WHERE matricule = ?', [id]);
    
    if (rows.length === 0) {
      return next(new AppError('Eleve not found', 404));
    }

    res.status(200).json({
      success: true,
      data: rows[0]
    });
  } catch (error) {
    next(error);
  }
};

export const createEleve = async (req: Request, res: Response, next: NextFunction) => {
  try {
    // Determine admin id from user or default
    const idAdmin = req.user?.id || 1; 

    const validatedData = eleveSchema.parse(req.body);
    
    // In real scenario matricule could be auto-increment or generated, depending on schema.
    // Assuming auto increment or generated by trigger.
    const { nom, prenom, dateNaissance, lieuNaissance, sexe, langue, photoURL, actif, idVilleNaissance } = validatedData;

    const [result]: any = await pool.query(
      `INSERT INTO Eleve (nom, prenom, dateNaissance, lieuNaissance, sexe, langue, photoURL, actif, idVilleNaissance, idAdmin, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW())`,
      [nom, prenom, dateNaissance, lieuNaissance, sexe, langue, photoURL, actif, idVilleNaissance, idAdmin]
    );

    res.status(201).json({
      success: true,
      message: 'Eleve created successfully',
      data: {
        matricule: result.insertId,
        ...validatedData
      }
    });
  } catch (error) {
    next(error);
  }
};

export const updateEleve = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const validatedData = eleveUpdateSchema.parse(req.body);

    if (Object.keys(validatedData).length === 0) {
      return res.status(400).json({ success: false, message: 'Nothing to update' });
    }

    let updateQuery = 'UPDATE Eleve SET ';
    const queryParams: any[] = [];
    const setClauses: string[] = [];

    for (const [key, value] of Object.entries(validatedData)) {
      setClauses.push(`${key} = ?`);
      queryParams.push(value);
    }

    updateQuery += setClauses.join(', ') + ' WHERE matricule = ?';
    queryParams.push(id);

    const [result]: any = await pool.query(updateQuery, queryParams);

    if (result.affectedRows === 0) {
      return next(new AppError('Eleve not found', 404));
    }

    res.status(200).json({
      success: true,
      message: 'Eleve updated successfully',
    });
  } catch (error) {
    next(error);
  }
};

export const deleteEleve = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const { id } = req.params;
    const [result]: any = await pool.query('DELETE FROM Eleve WHERE matricule = ?', [id]);

    if (result.affectedRows === 0) {
      return next(new AppError('Eleve not found', 404));
    }

    res.status(200).json({
      success: true,
      message: 'Eleve deleted successfully'
    });
  } catch (error) {
    next(error);
  }
};
